apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "kubernetes"
  containers:
  - name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.7.2
    imagePullPolicy: IfNotPresent
    args:
    - manager
    env:
    - name: vip_interface
      value: "ens34"
    - name: vip_address
      value: "172.16.40.120"
    - name: vip_arp
      value: "true"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: vip_leaderelection
      value: "false"
    - name: leaseDuration
      value: "600"
    - name: leaseRenewDeadline
      value: "540"
    - name: leaseRetryPeriod
      value: "60"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  volumes:
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes/admin.conf
      type: File
status: {}
